#ifndef ANALIZADORLEXICO_ERROS_H_


#define ERRO_ID_NON_DECLARADO 1
#define ERRO_DECLARA_FUNCION 2
#define ERRO_MOD_CONSTANTE 3
#define ERRO_LENDO_ARQUIVO 4
#define ERRO_ARQUIVO 5

#endif /* ANALIZADORLEXICO_ERROS_H_ */
